nelmio_api_doc:
    documentation:
        info:
            title: TLT-JS-Mentoring
            description: 
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/rest-api(?!/doc$) # Accepts routes under /api except /api/doc
